os:
  - linux
  - osx

language: node_js

node_js:
  - "0.10"
  - "0.11"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++ python libnss3-dev libudev-dev libgcrypt11-dev
  - npm install -g grunt-cli
  - npm install node-gyp -g

install:
  - npm install

notifications:
  email: false
